BINS=testexp testlog testpow testroot testtrigon

CXXFLAGS+=-I..  -static -O3

all: $(BINS)

testpow: testpow.o
	$(CXX) testpow.o -o testpow -static
testexp: testexp.o
	$(CXX) testexp.o -o testexp -static
testlog: testlog.o
	$(CXX) testlog.o -o testlog -static
testroot: testroot.o
	$(CXX) testroot.o -o testroot -static
testtrigon: testtrigon.o
	$(CXX) testtrigon.o -o testtrigon -static

clean:
	rm -f $(BINS) *.o
