BINS=mm_extract_ps mm_extract_pd

CXXFLAGS+=-I..  -static -Ofast -march=native

all: $(BINS)

mm_extract_ps: mm_extract_ps.o
	$(CXX) mm_extract_ps.o -o mm_extract_ps -static

mm_extract_pd: mm_extract_pd.o
	$(CXX) mm_extract_pd.o -o mm_extract_pd -static

clean:
	rm -f $(BINS) *.o
