# You may need to point it to the correct location
# of the Intel compiler binary.
CXX=icpc
BINS=testapproxlog 

CXXFLAGS+=-I.. -mkl  -O3 -xAVX 

all: $(BINS)

testapproxlog: testapproxlog.o
	$(CXX) testapproxlog.o -o testapproxlog -static -mkl

clean:
	rm -f $(BINS) *.o
